import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    borderBottomWidth: 1,
  },
  closeButton: { padding: 8 },
  section: {
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    marginHorizontal: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  scrollContent: { paddingVertical: 16 },
  inputGroup: { marginBottom: 16 },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    height: 54,
    borderRadius: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
  },
  inputIcon: { marginRight: 12 },
  input: { flex: 1, fontSize: 16 },
  textAreaContainer: {
    height: undefined,
    minHeight: 110,
    alignItems: "flex-start",
    paddingVertical: 14,
  },
  textArea: { minHeight: 82, textAlignVertical: "top" },
  footer: { padding: 16, borderTopWidth: 1 },
  card: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    marginHorizontal: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  deleteButton: { padding: 8, backgroundColor: "#ffeff0", borderRadius: 8 },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 54,
    borderRadius: 12,
    borderWidth: 1,
    marginHorizontal: 16,
    marginBottom: 40,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    minHeight: 400,
  },
  rowInput: { flexDirection: "row", justifyContent: "space-between" },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
  },
  sectionHeader: { paddingHorizontal: 16 },
  iconButton: { padding: 8, marginLeft: 4 },
  infoRow: { flexDirection: "row", alignItems: "center" },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  copyButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    borderRadius: 12,
  },
  ticketingInput: { borderWidth: 1, borderRadius: 8, padding: 8, fontSize: 16 },
  layoutTypeChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
  },
  layoutSection: { marginTop: 16 },
  layoutHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  organisationDescription: { marginBottom: 16 },
  modalTitle: { marginBottom: 16 },
  modalRow: { flexDirection: "row", gap: 10, marginTop: 24 },
  modalAction: { flex: 1 },
  organisationDesc: { marginBottom: 16, paddingHorizontal: 20 },
  sectionLabel: { marginBottom: 12, textTransform: "uppercase" as const },
  sectionLabelLg: { marginBottom: 16, textTransform: "uppercase" as const },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chipRadius8: { borderRadius: 8 },
  padding8: { padding: 8 },
  timeAlignCol: { alignItems: "center", width: 60 },
  flex1PadH12: { flex: 1, paddingHorizontal: 12 },
  dirRow: { flexDirection: "row" },
  flex1: { flex: 1 },
  mb16: { marginBottom: 16 },
  mb8: { marginBottom: 8 },
  fullWidth: { width: "100%" as const },
  maxH80pct: { maxHeight: "80%" as const },
  borderBox: { borderWidth: 1, borderRadius: 8, padding: 8 },
  actionBtns: { flexDirection: "row", gap: 10, marginTop: 20 },
  flex1MR8: { flex: 1, marginRight: 8 },
  w100: { width: 100 },
  textCenter: { textAlign: "center" as const },
  mt6: { marginTop: 6 },
  tagRowMT8: { flexDirection: "row", gap: 8, marginTop: 8 },
  mt16: { marginTop: 16 },
  flex1ML12: { flex: 1, marginLeft: 12 },
  mb12: { marginBottom: 12 },
  w40: { width: 40 },
  padding16: { padding: 16 },
  pt0: { paddingTop: 0 },
  flex2: { flex: 2 },
  minH400: { minHeight: 400 },
  rowBetweenMB16: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  mb24: { marginBottom: 24 },
  mt24: { marginTop: 24 },
  negMt8Mb8: { marginTop: -8, marginBottom: 8 },
  ml8: { marginLeft: 8 },
  mb16PadH20: { marginBottom: 16, paddingHorizontal: 20 },
  dashedBorder: { borderStyle: "dashed" as const },
  dashedBorderMT12: { borderStyle: "dashed" as const, marginTop: 12 },
  height200: { height: 200 },
  mb0ZIndex1000: { marginBottom: 0, zIndex: 1000 },
  qrContainer: {
    padding: 16,
    backgroundColor: "white",
    borderRadius: 16,
    alignSelf: "center" as const,
  },
  fontSize10Bold: { fontSize: 10, fontWeight: "bold" as const },
  fontSize10Semi: { fontSize: 10, fontWeight: "600" as const },
  tagChip: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  eventHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 4,
    gap: 6,
  },
  ml8w600: { marginLeft: 8, fontWeight: "600" as const },
  organisationContainer: { paddingHorizontal: 20, paddingBottom: 100 },
});
