source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '!= 1.15.0', '!= 1.15.1', '>= 1.16.0'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '>= 1.26.0', '< 2.0'
# concurrent-ruby >= 1.3.7 fixes GHSA-h8w8-99g7-qmvj (AtomicReference#update livelock).
# The old '< 1.3.4' cap worked around a missing-logger crash, already handled by `gem 'logger'` below.
gem 'concurrent-ruby', '>= 1.3.7'

# Ruby 3.4.0+ has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
