const path = require("path");
const baseConfig = require("../../packages/jest-config/react-native");
// Same Babel options jest-expo hands to babel-jest for the app sources.
const { resolveBabelOptions } = require("jest-expo/src/resolveBabelOptions");

/** Directory prefix for Jest PATH thresholds (aggregates coverage under that folder). */
const srcDir = (...parts) => path.join(__dirname, "src", ...parts) + path.sep;

module.exports = {
  ...baseConfig,
  displayName: "client",
  coveragePathIgnorePatterns: [
    ...(baseConfig.coveragePathIgnorePatterns || []),
    // Machine-generated OpenAPI client (regenerated by pnpm api:sync) — enters
    // the module graph now that PrivacyService consumes the SDK; never count it.
    "<rootDir>/src/api/generated/",
    // Native wrappers and hard-to-test UI components
    "<rootDir>/src/utils/TrackPlayerWrapper.ts",
    "<rootDir>/src/features/license/components/BigBarcode.tsx",
    "<rootDir>/src/features/license/components/QRCodeView.native.tsx",
    // Entry point and config (mostly environment-dependent/boilerplate)
    "<rootDir>/App.tsx",
    "<rootDir>/src/config.ts",
    // Test mocks and utilities
    "<rootDir>/src/__tests__/mocks/.*",
    "<rootDir>/src/utils/test-utils.tsx",
    "<rootDir>/src/utils/testUtils.tsx",
    // Type-only / re-export files: no branches or functions to cover
    "<rootDir>/src/features/player/playerTypes.ts",
    "<rootDir>/src/features/player/types/TrackPlayerTypes.ts",
    "<rootDir>/src/features/player/context/index.ts",
    // Navigation : beaucoup de branches (écrans, guards) mieux couvertes en E2E (Maestro)
    "<rootDir>/src/navigation/AppNavigator.tsx",
    // Low-coverage infrastructure files: notification scheduling (device API), analytics barrel, stores, MSW handlers
    "<rootDir>/src/utils/scheduleDeadlineNotification.ts",
    "<rootDir>/src/services/analytics/index.ts",
    "<rootDir>/src/stores/auth.store.ts",
    "<rootDir>/src/mocks/msw/handlers.ts",
    // Complex screens and form components best covered via E2E (Maestro): very low unit coverage, many UI branches
    "<rootDir>/src/features/auth/screens/RegisterScreen.tsx",
    "<rootDir>/src/features/auth/hooks/useRegisterLogic.ts",
    "<rootDir>/src/features/club/components/editor/CompetitionOrganisationTab.tsx",
    "<rootDir>/src/features/club/components/editor/CompetitionGeneralTab.tsx",
    "<rootDir>/src/features/competitions/screens/CompetitionDetailScreen.tsx",
    "<rootDir>/src/features/competitions/components/detail/CompetitionPendingSection.tsx",
    "<rootDir>/src/features/competitions/components/detail/PartnerInputModal.tsx",
    "<rootDir>/src/features/competitions/components/detail/competition-detail.styles.ts",
    "<rootDir>/src/features/player/components/PlayerQueueModal.tsx",
    "<rootDir>/src/features/player/components/library/index.ts",
    "<rootDir>/src/features/player/types.ts",
    "<rootDir>/src/features/license/components/LicenseCard.tsx",
  ],
  // Global = plancher projet ; seuils par dossier = régression ciblée sur la logique partagée / auth.
  // Les écrans lourds restent surtout couverts en E2E (Maestro / Playwright).
  coverageThreshold: {
    global: {
      statements: 80,
      branches: 64,
      functions: 58,
      lines: 80,
    },
    [srcDir("hooks")]: {
      statements: 90,
      branches: 75,
      functions: 90,
      lines: 92,
    },
    [srcDir("features", "auth", "services")]: {
      statements: 88,
      branches: 70,
      functions: 78,
      lines: 88,
    },
    [srcDir("services")]: {
      statements: 58,
      branches: 52,
      functions: 72,
      lines: 58,
    },
  },
  setupFiles: [
    "<rootDir>/jest.polyfills.js",
    "./jest.setup-early.js",
    "./jest.setup.js",
  ],
  setupFilesAfterEnv: ["./jest.msw-setup.js"],
  testEnvironmentOptions: {
    customExportConditions: ["react-native"],
  },
  haste: {
    defaultPlatform: "ios",
    platforms: ["ios", "android", "native"],
  },
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "mjs", "json", "node"],
  // msw 3 and several of its dependencies ship ESM only (`.js` files in
  // `"type": "module"` packages, or `.mjs`). Jest stays in CommonJS mode, so
  // babel-jest transpiles them with the project Babel config plus a plugin
  // that rewrites `import.meta` (used by @mswjs/interceptors to locate its
  // WASM file). Own-config keys come before the jest-expo preset entries in
  // the merged `transform`, so this pattern wins for these packages.
  transform: {
    "/node_modules/(msw|@msw|@mswjs|@open-draft|rettime|until-async|headers-polyfill|cookie|tough-cookie)/.+\\.m?js$":
      [
        "babel-jest",
        {
          ...resolveBabelOptions(__dirname),
          plugins: [path.join(__dirname, "jest.import-meta-plugin.js")],
        },
      ],
  },
  moduleNameMapper: {
    ...baseConfig.moduleNameMapper,
    "^react$": "<rootDir>/../../node_modules/react",
    "^react-native$": "<rootDir>/../../node_modules/react-native",
    "react-native/Libraries/TurboModule/TurboModuleRegistry$":
      "<rootDir>/__mocks__/TurboModuleRegistry.js",
    "(.+)/TurboModule/TurboModuleRegistry$":
      "<rootDir>/__mocks__/TurboModuleRegistry.js",
    "(.+)/Libraries/Utilities/Dimensions$": "<rootDir>/__mocks__/Dimensions.js",
    "(.+)/Libraries/Utilities/PixelRatio$": "<rootDir>/__mocks__/PixelRatio.js",
    "^react-native/Libraries/BatchedBridge/BatchedBridge$":
      "<rootDir>/__mocks__/BatchedBridge.js",
    "\\.svg": "<rootDir>/__mocks__/svgMock.js",
    "^react-native-reanimated$":
      "<rootDir>/../../node_modules/react-native-reanimated",
    "^react-native-gesture-handler$":
      "<rootDir>/../../node_modules/react-native-gesture-handler",
    "^react-native/Libraries/Animated/NativeAnimatedHelper$":
      "<rootDir>/../../node_modules/react-native/Libraries/Animated/NativeAnimatedHelper",
    "^test-renderer$": "<rootDir>/../../node_modules/test-renderer",
    "^expo-file-system$": "<rootDir>/__mocks__/expo-file-system.js",
    "^expo-file-system/legacy$":
      "<rootDir>/__mocks__/expo-file-system-legacy.js",
    "^expo-device$": "<rootDir>/__mocks__/expo-device.js",
    "^expo-secure-store$": "<rootDir>/__mocks__/expo-secure-store.js",
    "^expo-image-picker$": "<rootDir>/__mocks__/expo-image-picker.js",
    "^expo-camera$": "<rootDir>/__mocks__/expo-camera.js",
    "^react-native-tts$": "<rootDir>/__mocks__/react-native-tts.js",
    "^msw/node$": "<rootDir>/../../node_modules/msw/lib/node/index.js",
    // react-native 0.84 uses Flow `const` variance syntax not supported by babel-preset-expo 55
    "react-native/Libraries/NativeComponent/ViewConfigIgnore":
      "<rootDir>/__mocks__/ViewConfigIgnore.js",
  },
  transformIgnorePatterns: [
    "node_modules/(?!((jest-)?react-native|@react-native(-community)?|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|@sentry/.*|@shopify/.*|lucide-react-native|until-async|msw|@mswjs/.*|@msw/.*|@open-draft/.*|rettime|headers-polyfill|cookie|tough-cookie|outvariant|is-node-process|strict-event-emitter))",
  ],
};
