// Style-only entry: the legal pages are static HTML generated by legal-plugin.ts,
// so this module exists purely to route their CSS through Vite's pipeline.
import './index.css';
import './legal.css';
