/**
 * Expo config plugin: withFaceIDiOS26Fix
 * =======================================
 *
 * Real native fix for the iOS 26 Face ID failure in expo-local-authentication 55.x.
 *
 * ROOT CAUSE (confirmed in node_modules/expo-local-authentication/ios/LocalAuthenticationModule.swift):
 *   Every biometrics probe (`hasHardwareAsync`, `isEnrolledAsync`, `getEnrolledLevelAsync`,
 *   plus the `isFaceIdDevice`/`isTouchIdDevice` helpers) calls
 *     LAContext.canEvaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, error:)
 *   inside an Expo `AsyncFunction`, which Expo dispatches on a BACKGROUND queue.
 *   On iOS 26 that call raises an Objective-C NSException. Swift's do/catch cannot
 *   catch an ObjC NSException, so it propagates to RN's TurboModule bridge:
 *     - Without a bridge patch  -> SIGABRT (_objc_terminate).
 *     - With patches/react-native@0.83.6.patch (which swallows the NSException at
 *       the bridge) -> the async call returns garbage, so hasHardwareAsync /
 *       isEnrolledAsync resolve false/undefined and Face ID "disappears".
 *
 * TWO-PART FIX (belt & suspenders), both applied to the pod's own source so they
 * ship inside the ExpoLocalAuthentication module (works in EAS prebuild + local prebuild):
 *   1. MAIN-THREAD DISPATCH: every canEvaluatePolicy / biometryType read is forced
 *      onto the main thread (LAContext on iOS 26 is main-thread sensitive).
 *   2. NSEXCEPTION CATCH: a tiny Objective-C shim wraps canEvaluatePolicy in
 *      @try/@catch (NSException). A thrown NSException is caught NATIVELY and turned
 *      into a safe `false`, so it never reaches the TurboModule bridge at all.
 *
 * MECHANISM:
 *   The ExpoLocalAuthentication podspec globs all h/m/swift files and sets
 *   DEFINES_MODULE => YES, so any .h/.m we drop into the pod's ios/ dir is compiled
 *   into the module and its public header is visible to the pod's Swift files via
 *   the CocoaPods-generated umbrella header (no bridging header needed).
 *
 *   This plugin runs as a `withDangerousMod` on the "ios" platform (i.e. at
 *   prebuild, before pod install) and rewrites the files in
 *   node_modules/expo-local-authentication/ios so the changes are present when
 *   CocoaPods copies/compiles the pod. It is fully idempotent: it overwrites with
 *   canonical content and no-ops if the content already matches.
 *
 * VERIFICATION LIMIT:
 *   Native behaviour can ONLY be confirmed by an
 *     eas build --profile preview --platform ios
 *   installed on a PHYSICAL iOS 26 device. It cannot be validated from CI/JS.
 */

const { withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const SHIM_HEADER_NAME = "EXFaceIDExceptionShim.h";
const SHIM_IMPL_NAME = "EXFaceIDExceptionShim.m";
const SWIFT_MODULE_NAME = "LocalAuthenticationModule.swift";
const PODSPEC_NAME = "ExpoLocalAuthentication.podspec";

const MARKER = "FFD_IOS26_FACEID_FIX_V1";

const SHIM_HEADER = `// ${MARKER}
// Generated by apps/client/plugins/withFaceIDiOS26Fix.js — DO NOT EDIT BY HAND.
// Objective-C exception-catching shim for LAContext.canEvaluatePolicy on iOS 26.
// Swift cannot catch ObjC NSExceptions; this wraps the call so a thrown
// NSException becomes a safe result (canEvaluate = NO) instead of crashing the
// TurboModule bridge.
//
// The result is returned via a small object rather than an NSError** out-param:
// a trailing NSError** would be folded by Swift's ObjC importer into a throwing
// method, which we do NOT want here (we must return the LAContext error object,
// not throw). Verified against the iOS 26.2 SDK: this imports to Swift as
//   EXFaceIDExceptionShim.evaluatePolicy(_:with:) -> EXFaceIDPolicyResult
#import <Foundation/Foundation.h>
#import <LocalAuthentication/LocalAuthentication.h>

NS_ASSUME_NONNULL_BEGIN

@interface EXFaceIDPolicyResult : NSObject
@property (nonatomic, assign) BOOL canEvaluate;
@property (nonatomic, strong, nullable) NSError *error;
@end

@interface EXFaceIDExceptionShim : NSObject

/// Calls -[LAContext canEvaluatePolicy:error:] inside @try/@catch.
/// On an ObjC NSException (observed on iOS 26) returns canEvaluate = NO, error = nil.
+ (EXFaceIDPolicyResult *)evaluatePolicy:(LAPolicy)policy withContext:(LAContext *)context;

@end

NS_ASSUME_NONNULL_END
`;

const SHIM_IMPL = `// ${MARKER}
// Generated by apps/client/plugins/withFaceIDiOS26Fix.js — DO NOT EDIT BY HAND.
#import "${SHIM_HEADER_NAME}"

@implementation EXFaceIDPolicyResult
@end

@implementation EXFaceIDExceptionShim

+ (EXFaceIDPolicyResult *)evaluatePolicy:(LAPolicy)policy withContext:(LAContext *)context {
  EXFaceIDPolicyResult *result = [EXFaceIDPolicyResult new];
  @try {
    NSError *error = nil;
    result.canEvaluate = [context canEvaluatePolicy:policy error:&error];
    result.error = error;
  } @catch (NSException *exception) {
    NSLog(@"[FaceIDiOS26Fix] NSException from canEvaluatePolicy(%ld): %@ - %@",
          (long)policy, exception.name, exception.reason);
    result.canEvaluate = NO;
    result.error = nil;
  }
  return result;
}

@end
`;

// Canonical, fully-fixed replacement for LocalAuthenticationModule.swift.
// Every canEvaluatePolicy call goes through EXFaceIDExceptionShim (ObjC @try/@catch)
// AND is executed on the main thread. authenticateAsync's evaluatePolicy is also
// dispatched to the main thread and reads biometryType/usage-description safely.
const SWIFT_MODULE = `// ${MARKER}
// Generated by apps/client/plugins/withFaceIDiOS26Fix.js — DO NOT EDIT BY HAND.
// See apps/client/plugins/withFaceIDiOS26Fix.js for the root-cause writeup.
import ExpoModulesCore
import LocalAuthentication

// Runs \`work\` on the main thread. If already on main, runs inline (avoids the
// deadlock that DispatchQueue.main.sync would cause when called from main).
private func onMainThread<T>(_ work: () -> T) -> T {
  if Thread.isMainThread {
    return work()
  }
  return DispatchQueue.main.sync(execute: work)
}

// Main-thread + ObjC-NSException-safe wrapper around LAContext.canEvaluatePolicy.
// On iOS 26 the underlying call can raise an ObjC NSException which Swift cannot
// catch; the shim converts it to a safe \`false\` before it reaches the RN bridge.
private func safeCanEvaluatePolicy(_ context: LAContext, _ policy: LAPolicy, _ error: inout NSError?) -> Bool {
  return onMainThread {
    let result = EXFaceIDExceptionShim.evaluatePolicy(policy, with: context)
    error = result.error as NSError?
    return result.canEvaluate
  }
}

public class LocalAuthenticationModule: Module {
  public func definition() -> ModuleDefinition {
    Name("ExpoLocalAuthentication")

    AsyncFunction("hasHardwareAsync") { () -> Bool in
      let context = LAContext()
      var error: NSError?
      let isSupported: Bool = safeCanEvaluatePolicy(context, LAPolicy.deviceOwnerAuthenticationWithBiometrics, &error)
      let isAvailable: Bool = isSupported || error?.code != LAError.biometryNotAvailable.rawValue

      return isAvailable
    }

    AsyncFunction("isEnrolledAsync") { () -> Bool in
      let context = LAContext()
      var error: NSError?
      let isSupported: Bool = safeCanEvaluatePolicy(context, LAPolicy.deviceOwnerAuthenticationWithBiometrics, &error)
      let isEnrolled: Bool = (isSupported && error == nil) || error?.code == LAError.biometryLockout.rawValue

      return isEnrolled
    }

    AsyncFunction("supportedAuthenticationTypesAsync") { () -> [Int] in
      var supportedAuthenticationTypes: [Int] = []

      if isTouchIdDevice() {
        supportedAuthenticationTypes.append(AuthenticationType.fingerprint.rawValue)
      }

      if isFaceIdDevice() {
        supportedAuthenticationTypes.append(AuthenticationType.facialRecognition.rawValue)
      }

      return supportedAuthenticationTypes
    }

    AsyncFunction("getEnrolledLevelAsync") { () -> Int in
      let context = LAContext()
      var error: NSError?

      var level: Int = SecurityLevel.none.rawValue

      let isAuthenticationSupported: Bool = safeCanEvaluatePolicy(context, LAPolicy.deviceOwnerAuthentication, &error)
      if isAuthenticationSupported && error == nil {
        level = SecurityLevel.secret.rawValue
      }

      let isBiometricsSupported: Bool = safeCanEvaluatePolicy(context, LAPolicy.deviceOwnerAuthenticationWithBiometrics, &error)

      if isBiometricsSupported && error == nil {
        level = SecurityLevel.biometric.rawValue
      }

      return level
    }

    AsyncFunction("authenticateAsync") { (options: LocalAuthenticationOptions, promise: Promise) -> Void in
      var warningMessage: String?
      let reason = options.promptMessage
      let cancelLabel = options.cancelLabel
      let fallbackLabel = options.fallbackLabel
      let disableDeviceFallback = options.disableDeviceFallback

      if isFaceIdDevice() {
        let usageDescription = Bundle.main.object(forInfoDictionaryKey: "NSFaceIDUsageDescription")

        if usageDescription == nil {
          warningMessage = "FaceID is available but has not been configured. To enable FaceID, provide \`NSFaceIDUsageDescription\`."
        }
      }

      let context = LAContext()

      if fallbackLabel != nil {
        context.localizedFallbackTitle = fallbackLabel
      }

      if cancelLabel != nil {
        context.localizedCancelTitle = cancelLabel
      }

      context.interactionNotAllowed = false

      let policyForAuth = disableDeviceFallback ? LAPolicy.deviceOwnerAuthenticationWithBiometrics : LAPolicy.deviceOwnerAuthentication

      if disableDeviceFallback {
        if warningMessage != nil {
          // If the warning message is set (NSFaceIDUsageDescription is not configured) then we can't use
          // authentication with biometrics — it would crash, so let's just resolve with no success.
          // We could reject, but we already resolve even if there are any errors, so sadly we would need to introduce a breaking change.
          return promise.resolve([
            "success": false,
            "error": "missing_usage_description",
            "warning": warningMessage as Any
          ])
        }
      }

      // iOS 26: evaluatePolicy (which presents the Face ID / passcode UI) must run
      // on the main thread. The completion handler is invoked on an arbitrary queue,
      // so we resolve the promise from there directly.
      onMainThread {
        context.evaluatePolicy(policyForAuth, localizedReason: reason ?? "") { success, error in
          var err: String?

          if let error = error as? NSError {
            err = convertErrorCode(error: error)
          }

          promise.resolve([
            "success": success,
            "error": err as Any,
            "warning": warningMessage as Any
          ])
        }
      }
    }
  }
}

func isFaceIdDevice() -> Bool {
  let context = LAContext()
  var error: NSError?
  _ = safeCanEvaluatePolicy(context, LAPolicy.deviceOwnerAuthenticationWithBiometrics, &error)

  return onMainThread { context.biometryType == LABiometryType.faceID }
}

func isTouchIdDevice() -> Bool {
  let context = LAContext()
  var error: NSError?
  _ = safeCanEvaluatePolicy(context, LAPolicy.deviceOwnerAuthenticationWithBiometrics, &error)

  return onMainThread { context.biometryType == LABiometryType.touchID }
}

func convertErrorCode(error: NSError) -> String {
  switch error.code {
  case LAError.systemCancel.rawValue:
    return "system_cancel"
  case LAError.appCancel.rawValue:
    return "app_cancel"
  case LAError.biometryLockout.rawValue:
    return "lockout"
  case LAError.userFallback.rawValue:
    return "user_fallback"
  case LAError.userCancel.rawValue:
    return "user_cancel"
  case LAError.biometryNotAvailable.rawValue:
    return "not_available"
  case LAError.invalidContext.rawValue:
    return "invalid_context"
  case LAError.biometryNotEnrolled.rawValue:
    return "not_enrolled"
  case LAError.passcodeNotSet.rawValue:
    return "passcode_not_set"
  case LAError.authenticationFailed.rawValue:
    return "authentication_failed"
  default:
      return "unknown: \\(error.code), \\(error.localizedDescription)"
  }
}

enum AuthenticationType: Int {
  case fingerprint = 1
  case facialRecognition = 2
 }

enum SecurityLevel: Int {
  case none = 0
  case secret = 1
  // We return any biometric as strong biometric, because there are currently no iOS devices with weak biometric options.
  case biometric = 3
 }
`;

function resolvePodIosDir(projectRoot) {
  // node-linker=hoisted + symlink=false => packages live flat in the ROOT
  // node_modules, not apps/client/node_modules. Resolve from the module id so we
  // find it regardless of where it was hoisted.
  const candidates = [];
  try {
    const pkgJson = require.resolve("expo-local-authentication/package.json", {
      paths: [projectRoot],
    });
    candidates.push(path.join(path.dirname(pkgJson), "ios"));
  } catch {
    // fall through to manual candidates
  }
  candidates.push(
    path.join(projectRoot, "node_modules", "expo-local-authentication", "ios"),
    path.join(
      projectRoot,
      "..",
      "..",
      "node_modules",
      "expo-local-authentication",
      "ios",
    ),
  );
  for (const dir of candidates) {
    if (fs.existsSync(path.join(dir, SWIFT_MODULE_NAME))) {
      return dir;
    }
  }
  return null;
}

// Ensure the shim header is exposed to the pod's Swift files. For a pod with
// DEFINES_MODULE => YES, CocoaPods includes all source_files headers in the
// generated umbrella by default, so Swift already sees EXFaceIDExceptionShim.
// We additionally pin `s.public_header_files` to be explicit and robust across
// CocoaPods versions. Idempotent: no-op if already patched.
function patchPodspec(iosDir) {
  const podspecPath = path.join(iosDir, PODSPEC_NAME);
  if (!fs.existsSync(podspecPath)) {
    return false;
  }
  let contents = fs.readFileSync(podspecPath, "utf8");
  if (contents.includes(MARKER)) {
    return false; // already patched
  }
  const anchor = 's.source_files = "**/*.{h,m,swift}"';
  if (!contents.includes(anchor)) {
    // podspec shape changed upstream; skip silently, the default umbrella
    // behaviour still exposes the header.
    return false;
  }
  const injection =
    `${anchor}\n` +
    `  # ${MARKER}: expose the ObjC exception shim header via the pod module map\n` +
    `  s.public_header_files = "**/*.h"`;
  contents = contents.replace(anchor, injection);
  fs.writeFileSync(podspecPath, contents);
  return true;
}

function writeIfChanged(filePath, contents) {
  try {
    if (
      fs.existsSync(filePath) &&
      fs.readFileSync(filePath, "utf8") === contents
    ) {
      return false;
    }
  } catch {
    // ignore read errors, just write
  }
  fs.writeFileSync(filePath, contents);
  return true;
}

function applyFix(projectRoot) {
  const iosDir = resolvePodIosDir(projectRoot);
  if (!iosDir) {
    console.warn(
      "[withFaceIDiOS26Fix] Could not locate expo-local-authentication/ios; skipping (Face ID iOS 26 fix NOT applied).",
    );
    return;
  }

  const swiftPath = path.join(iosDir, SWIFT_MODULE_NAME);
  const headerPath = path.join(iosDir, SHIM_HEADER_NAME);
  const implPath = path.join(iosDir, SHIM_IMPL_NAME);

  // Safety guard: this plugin overwrites LocalAuthenticationModule.swift wholesale.
  // Confirm the current file is either the known-upstream original (verified
  // byte-identical for expo-local-authentication 55.0.15 AND 57.0.0) or our own
  // already-patched output. If upstream changes the file in a future release,
  // warn loudly so we notice and refresh SWIFT_MODULE rather than silently
  // clobbering a new implementation.
  if (fs.existsSync(swiftPath)) {
    const current = fs.readFileSync(swiftPath, "utf8");
    const isAlreadyPatched = current.includes(MARKER);
    // Signature of the unpatched upstream: raw canEvaluatePolicy in an AsyncFunction.
    const isKnownOriginal =
      current.includes(
        "let isSupported: Bool = context.canEvaluatePolicy(LAPolicy.deviceOwnerAuthenticationWithBiometrics, error: &error)",
      ) && !isAlreadyPatched;
    if (!isAlreadyPatched && !isKnownOriginal) {
      console.warn(
        "[withFaceIDiOS26Fix] WARNING: LocalAuthenticationModule.swift does not match " +
          "the known upstream original for this plugin version. The pinned SWIFT_MODULE " +
          "replacement may be stale — review apps/client/plugins/withFaceIDiOS26Fix.js " +
          "against the installed expo-local-authentication before trusting the Face ID fix.",
      );
    }
  }

  const wroteHeader = writeIfChanged(headerPath, SHIM_HEADER);
  const wroteImpl = writeIfChanged(implPath, SHIM_IMPL);
  const wroteSwift = writeIfChanged(swiftPath, SWIFT_MODULE);
  const patchedPodspec = patchPodspec(iosDir);

  console.log(
    `[withFaceIDiOS26Fix] Applied iOS 26 Face ID fix in ${iosDir} ` +
      `(header:${wroteHeader ? "written" : "up-to-date"}, ` +
      `impl:${wroteImpl ? "written" : "up-to-date"}, ` +
      `swift:${wroteSwift ? "written" : "up-to-date"}, ` +
      `podspec:${patchedPodspec ? "patched" : "up-to-date"}).`,
  );
}

function withFaceIDiOS26Fix(config) {
  return withDangerousMod(config, [
    "ios",
    async (modConfig) => {
      applyFix(modConfig.modRequest.projectRoot);
      return modConfig;
    },
  ]);
}

module.exports = withFaceIDiOS26Fix;
