/**
 * Expo config plugin: withFirebaseHeadlessLaunch
 * ==============================================
 *
 * Lets the JS root skip mounting <App /> when iOS launched the app in the
 * background to deliver a data-only (content-available) push (#40).
 *
 * WHY A PLUGIN IS REQUIRED
 *   The project is managed: ios/ is generated by prebuild and gitignored, so
 *   the AppDelegate cannot be edited by hand.
 *
 * WHAT IT DOES, AND WHY IT IS THE ONLY WORKING SHAPE
 *   RNFB sets `isHeadless` in two places, and only one of them creates the key:
 *
 *   1. `+[RNFBMessagingModule addCustomPropsToUserProps:withLaunchOptions:]`
 *      SEEDS it — NO normally, YES when launchOptions carry a remote
 *      notification and the app is in the background.
 *   2. Its UIApplicationDidFinishLaunching observer only UPDATES an existing
 *      key (`RNFBMessaging+NSNotificationCenter.m`):
 *
 *          if ([appPropertiesDict objectForKey:@"isHeadless"] != nil && ...)
 *
 *   So without (1) the prop never exists and (2) is a no-op. The generated
 *   AppDelegate calls `startReactNative(withModuleName:in:launchOptions:)`,
 *   the overload WITHOUT initialProperties — hence nothing seeds it today.
 *   This plugin switches to the four-argument overload declared in
 *   RCTReactNativeFactory.h and feeds it (1).
 *
 *   Note that (2) reaches for `RCTRootView.appProperties`, which does not match
 *   under the New Architecture. That path is therefore likely inert here — but
 *   it is not the one that matters: a headless launch is decided at launch
 *   time, from launchOptions, which is exactly what (1) reads.
 *
 * NOT APPLIED WITHOUT FIREBASE
 *   app.config.js only registers this plugin inside its FIREBASE_ENABLED
 *   branch, so a variant built without a Firebase config file never emits a
 *   reference to RNFBMessaging and keeps prebuilding.
 *
 * VERIFICATION LIMIT
 *   Textual patching and prebuild output are verifiable here; COMPILATION AND
 *   RUNTIME ARE NOT. Confirming this needs a native build and a data-only push
 *   to a killed app on a real device (see the acceptance criteria of #40).
 */

const { withAppDelegate, withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const BRIDGING_IMPORT = "#import <RNFBMessaging/RNFBMessagingModule.h>";
const SEED_CALL =
  "RNFBMessagingModule.addCustomProps(toUserProps: nil, withLaunchOptions: launchOptions)";

/** The exact call emitted by the Expo 57 prebuild template. */
const TARGET_CALL = `factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions)`;

const PATCHED_CALL = `factory.startReactNative(
      withModuleName: "main",
      in: window,
      initialProperties: ${SEED_CALL},
      launchOptions: launchOptions)`;

/**
 * The whole decision, as a pure function so it can be tested without driving a
 * prebuild. Returns the patched AppDelegate source, or the input unchanged when
 * the patch is already present.
 */
function patchAppDelegate(contents, language) {
  if (language !== "swift") {
    // Fail loudly: silently skipping would ship a build where headless
    // launches still mount the whole tree, with nothing to show for it.
    throw new Error(
      `[withFirebaseHeadlessLaunch] expected a Swift AppDelegate, got "${language}". ` +
        "The Expo template changed; update this plugin rather than ignoring it.",
    );
  }

  if (contents.includes("addCustomProps(toUserProps:")) {
    return contents; // idempotent — prebuild may run repeatedly
  }

  if (!contents.includes(TARGET_CALL)) {
    throw new Error(
      "[withFirebaseHeadlessLaunch] could not find the startReactNative call to patch. " +
        "The Expo AppDelegate template changed; re-derive TARGET_CALL from a fresh prebuild.",
    );
  }

  return contents.replace(TARGET_CALL, PATCHED_CALL);
}

function withAppDelegatePatch(config) {
  return withAppDelegate(config, (cfg) => {
    cfg.modResults.contents = patchAppDelegate(
      cfg.modResults.contents,
      cfg.modResults.language,
    );
    return cfg;
  });
}

function withBridgingHeaderImport(config) {
  return withDangerousMod(config, [
    "ios",
    (cfg) => {
      const iosRoot = path.join(cfg.modRequest.platformProjectRoot);
      // The bridging header is named after the variant, which changes per
      // EXPO_PUBLIC_APP_ENV — find it rather than hardcoding a name.
      const match = fs
        .readdirSync(iosRoot, { withFileTypes: true })
        .filter((e) => e.isDirectory())
        .map((e) => path.join(iosRoot, e.name))
        .flatMap((dir) =>
          fs
            .readdirSync(dir)
            .filter((f) => f.endsWith("-Bridging-Header.h"))
            .map((f) => path.join(dir, f)),
        );

      if (match.length === 0) {
        throw new Error(
          "[withFirebaseHeadlessLaunch] no *-Bridging-Header.h found; " +
            "the Swift AppDelegate cannot reach the Objective-C RNFB header.",
        );
      }

      for (const header of match) {
        const current = fs.readFileSync(header, "utf8");
        if (current.includes(BRIDGING_IMPORT)) continue;
        fs.writeFileSync(header, `${current.trimEnd()}\n${BRIDGING_IMPORT}\n`);
      }

      return cfg;
    },
  ]);
}

module.exports = function withFirebaseHeadlessLaunch(config) {
  return withBridgingHeaderImport(withAppDelegatePatch(config));
};

// Exported for the unit test; not part of the plugin contract.
module.exports.patchAppDelegate = patchAppDelegate;
module.exports.TARGET_CALL = TARGET_CALL;
