export {
  COMPETITION_TYPES,
  EVENT_KINDS,
  ALLOWED_EVENT_KINDS_BY_COMPETITION_TYPE,
  LEVELS_ALLOWED_FOR_PROXIMITE_CLASSIFICATRICE,
  getAllowedCoupleAgeClassesForEvent,
  getAllowedSoloAgeClassesForEvent,
  isAgeGroupEligibleForEvent,
  isLevelEligibleForClassificatriceEvent,
  checkParticipationEligibility,
  getAllowedEventKindsForCompetitionType,
  isEventKindAllowedForCompetitionType,
  isLevelAllowedForProximiteClassificatrice,
  type CompetitionTypeValue,
  type EventKindValue,
  type ProximiteClassificatriceLevel,
  type ParticipationCheckResult,
  type ParticipationParams,
} from "./participation-rules.util";
