export {
  getAgeAtReferenceDate,
  getReferenceYear,
  computeSoloAgeGroup,
  computeCoupleAgeGroup,
  isCoupleEspoirEligible,
  ESPOIR_AGE_GROUP,
  ESPOIR_MAX_AGE,
  getAllowedLevelsForAgeGroup,
  COUPLE_AGE_GROUPS,
  SOLO_AGE_GROUPS,
  COMPETITION_LEVELS,
  type CoupleAgeGroup,
  type SoloAgeGroup,
  type CompetitionLevel,
} from "./age-group.util";
